"""add uses_location_split no model sector

Revision ID: 000d0e83ba29
Revises: 93b7a596f0ba
Create Date: 2026-07-18 12:43:18.040423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000d0e83ba29'
down_revision: Union[str, Sequence[str], None] = '93b7a596f0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_items', 'expected_quantity_fundo')
    op.drop_column('balance_items', 'expected_quantity_frente')
    op.add_column('sectors', sa.Column('uses_location_split', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectors', 'uses_location_split')
    op.add_column('balance_items', sa.Column('expected_quantity_frente', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=True))
    op.add_column('balance_items', sa.Column('expected_quantity_fundo', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
