"""add nova tabela container_count

Revision ID: 233d1db27bb7
Revises: 000d0e83ba29
Create Date: 2026-07-20 15:29:21.417012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233d1db27bb7'
down_revision: Union[str, Sequence[str], None] = '000d0e83ba29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('tracks_container', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('materials', sa.Column('sale_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'sale_price')
    op.drop_column('materials', 'tracks_container')
    # ### end Alembic commands ###
