"""campo quantity_ordered adicionado

Revision ID: 39ca3144b219
Revises: e7999fc1100b
Create Date: 2026-08-01 11:42:17.642130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '39ca3144b219'
down_revision: Union[str, Sequence[str], None] = 'e7999fc1100b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_name_category', 'materials', ['name', 'category_id'])

    op.add_column('orders', sa.Column('quantity_ordered', sa.DECIMAL(precision=11, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity_ordered')

    op.drop_constraint('uq_name_category', 'materials', type_='unique')
    # ### end Alembic commands ###
