"""alterando models

Revision ID: 4ba2de0e6ce4
Revises: b3de816f7116
Create Date: 2026-07-15 13:09:07.983807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ba2de0e6ce4'
down_revision: Union[str, Sequence[str], None] = 'b3de816f7116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Remover a dependência da chave estrangeira
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    
    # 2. Apagar a tabela antiga de roles para limpar o banco
    op.drop_table('roles')
    
    # 3. Apagar a coluna antiga de números (role_id)
    op.drop_column('users', 'role_id')
    
    # 4. Criar o tipo ENUM no PostgreSQL fisicamente
    roles_enum = postgresql.ENUM('PIZZARIA', 'BAR', 'COZINHA', 'ADMIN', name='roles')
    roles_enum.create(op.get_bind())
    
    # 5. Adicionar a coluna nova (já com o nome correto 'role' e tipagem ENUM)
    op.add_column('users', sa.Column('role', roles_enum, nullable=False, server_default='PIZZARIA'))
    
    # 6. Remover a quantidade estática (O padrão Ledger que implementamos)
    op.drop_column('materials', 'quantity')
    
    # 7. Alterar o location para aceitar nulo (Preparando o sistema para o Bar)
    op.alter_column('movements', 'location',
               existing_type=postgresql.ENUM('FUNDO', 'FRENTE', name='location'),
               nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.alter_column('users', 'role_id',
               existing_type=sa.Enum('PIZZARIA', 'BAR', 'COZINHA', 'ADMIN', name='roles'),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('movements', 'location',
               existing_type=postgresql.ENUM('FUNDO', 'FRENTE', name='location'),
               nullable=False)
    op.add_column('materials', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    # ### end Alembic commands ###
