"""add coluna description na tabela container_counts e order

Revision ID: 5873276b0dab
Revises: 92d76ead3c99
Create Date: 2026-07-20 16:19:21.365512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5873276b0dab'
down_revision: Union[str, Sequence[str], None] = '92d76ead3c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_counts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'description')
    op.drop_column('container_counts', 'description')
    # ### end Alembic commands ###
