"""novos campos em order

Revision ID: 756b67a73c44
Revises: a87f25e1d5e8
Create Date: 2026-07-23 11:37:02.012370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '756b67a73c44'
down_revision: Union[str, Sequence[str], None] = 'a87f25e1d5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderstatus RENAME VALUE 'PENDENTE' TO 'SOLICITADO'")
    op.execute("ALTER TYPE orderstatus ADD VALUE 'PEDIDO_REALIZADO' AFTER 'SOLICITADO'")

    op.alter_column('orders', 'order_date', new_column_name='requested_at')

    op.alter_column(
        'orders', 'received_date',
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
    )

    op.add_column('orders', sa.Column('ordered_by', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'orders_ordered_by_fkey', 'orders', 'users', ['ordered_by'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ordered_by_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'supplier_name')
    op.drop_column('orders', 'ordered_at')
    op.drop_column('orders', 'ordered_by')

    op.alter_column(
        'orders', 'received_date',
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
    )

    op.alter_column('orders', 'requested_at', new_column_name='order_date')

    # Downgrade de enum: precisa recriar sem PEDIDO_REALIZADO (Postgres não remove valor de enum diretamente)
    op.execute("ALTER TYPE orderstatus RENAME VALUE 'SOLICITADO' TO 'PENDENTE'")
    # ### end Alembic commands ###
