"""initial schema

Revision ID: 80f4fdcce0aa
Revises: 
Create Date: 2026-07-13 17:03:50.253677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f4fdcce0aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'sector_id', name='uq_name_sector')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('balances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='balancestatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'sector_id', name='uq_sector_week')
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('expected_quantity', sa.DECIMAL(precision=11, scale=2), nullable=False),
    sa.Column('counted_quantity', sa.DECIMAL(precision=11, scale=2), nullable=False),
    sa.Column('difference', sa.DECIMAL(precision=11, scale=2), nullable=False),
    sa.Column('revised_expected_quantity', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('counted_by', sa.UUID(), nullable=False),
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('revised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_quantity_fundo', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('expected_quantity_frente', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('counted_quantity_fundo', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('counted_quantity_frente', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['balances.id'], ),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('balance_id', 'material_id', name='uq_balance_material')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quantity_requested', sa.DECIMAL(precision=11, scale=2), nullable=False),
    sa.Column('quantity_received', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'RECEBIDO', 'NAO_ENTREGUE', name='orderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Enum('ENTRADA', 'SAIDA', name='type'), nullable=False),
    sa.Column('location', sa.Enum('FUNDO', 'FRENTE', name='location'), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_date'), 'movements', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_date'), table_name='movements')
    op.drop_table('movements')
    op.drop_table('orders')
    op.drop_table('balance_items')
    op.drop_table('materials')
    op.drop_table('balances')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('sectors')
    op.drop_table('roles')
    # ### end Alembic commands ###
