"""add nova tabela container_count 2

Revision ID: 92d76ead3c99
Revises: 233d1db27bb7
Create Date: 2026-07-20 15:43:26.295694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d76ead3c99'
down_revision: Union[str, Sequence[str], None] = '233d1db27bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_counts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('count_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('counted_cascos', sa.Integer(), nullable=False),
    sa.Column('expected_from_sales', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), sa.Computed('counted_cascos - expected_from_sales', persisted=True), nullable=False),
    sa.Column('unit_sale_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('value_impact', sa.DECIMAL(precision=10, scale=2), sa.Computed('(counted_cascos - expected_from_sales) * unit_sale_price', persisted=True), nullable=False),
    sa.Column('counted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_counts')
    # ### end Alembic commands ###
