"""tabela_movement_orderid_para_nulo_add_transfer_ref

Revision ID: 93b7a596f0ba
Revises: 4ba2de0e6ce4
Create Date: 2026-07-16 12:42:21.742931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b7a596f0ba'
down_revision: Union[str, Sequence[str], None] = '4ba2de0e6ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('transfer_ref', sa.UUID(), nullable=True))
    op.add_column('movements', sa.Column('quantity', sa.DECIMAL(precision=11, scale=2), nullable=False))
    op.alter_column('movements', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_movements_transfer_ref'), 'movements', ['transfer_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_transfer_ref'), table_name='movements')
    op.alter_column('movements', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('movements', 'quantity')
    op.drop_column('movements', 'transfer_ref')
    # ### end Alembic commands ###
