"""tornando code unico

Revision ID: b3de816f7116
Revises: 80f4fdcce0aa
Create Date: 2026-07-15 12:38:43.838084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3de816f7116'
down_revision: Union[str, Sequence[str], None] = '80f4fdcce0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balances', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('balances', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
