"""alterando code para code_hash

Revision ID: e7999fc1100b
Revises: 756b67a73c44
Create Date: 2026-07-23 14:15:50.530163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7999fc1100b'
down_revision: Union[str, Sequence[str], None] = '756b67a73c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code_hash', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(op.f('users_code_key'), 'users', type_='unique')
    op.drop_column('users', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_code_key'), 'users', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'code_hash')
    # ### end Alembic commands ###
