"""adicionando server default no status order

Revision ID: f3f66c849153
Revises: 39ca3144b219
Create Date: 2026-08-06 11:59:07.010057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f66c849153'
down_revision: Union[str, Sequence[str], None] = '39ca3144b219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('SOLICITADO', 'PEDIDO_REALIZADO', 'RECEBIDO', 'NAO_ENTREGUE', name='orderstatus'),
               type_=sa.Enum('SOLICITADO', 'PEDIDO_REALIZADO', 'RECEBIDO', 'NAO_ENTREGUE', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('SOLICITADO', 'PEDIDO_REALIZADO', 'RECEBIDO', 'NAO_ENTREGUE', name='orderstatus'),
               type_=postgresql.ENUM('SOLICITADO', 'PEDIDO_REALIZADO', 'RECEBIDO', 'NAO_ENTREGUE', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
